version: '3.7'
services:
  mysql:
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - '8080:8080'
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/usr/src/app'
    restart: on-failure
    user: 1000:1000
  nginx:
    image: nginx:1.19.0-alpine
    restart: on-failure
    volumes:
      - './public/:/usr/src/app'
      - './docker/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
    depends_on:
      - php