App\Entity\Cake:
  type: entity

  manyToMany:
    categories:
      targetEntity: App\Entity\Category
      inversedBy: cakes
      joinTable:
        name: cakes_categories
        joinColumns:
          cake_id:
            referencedColumnName: id
        inverseJoinColumn:
          category_id:
            referencedColumnName: id

  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    name:
      type: string

    description:
      type: string

    price:
      type: float