App\Entity\Category:
  type: entity

  manyToMany:
    cakes:
      targetEntity: App\Entity\Cake
      mappedBy: categories

  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
