App\Entity\Cooker:
  type: entity

  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    email:
      type: string
    roles:
      type: array
    password:
      type: string
