#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_cake_list:
  path: /cakes
  controller: App\Controller\CakeController::list

app_cake:
  path: /cake/{id}
  controller: App\Controller\CakeController::show

app_cake_create:
  path: /cakes/create
  controller: App\Controller\CakeController::create

search_cake:
  path: /cakes/search
  controller: App\Controller\CakeController::search

app_login:
  path: /login
  controller: App\Controller\SecurityController::login

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout